version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: consumption_reading
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d consumption_reading"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  consumption_reading:
    build: .
    container_name: consumption_reading_service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    env_file:
      - .env

  migrate:
    build: .
    command: npm run migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
