version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: consumption_reading
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  consumption_reading:
    build: .
    container_name: consumption_reading_service
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
